# Generated by Django 4.2.10 on 2024-02-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='Name')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email address')),
                ('social_media_link', models.CharField(blank=True, default='', max_length=155, null=True, verbose_name='Social media link')),
                ('highest_education', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Highest education')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good_credit_risk', models.BooleanField(blank=True, null=True, verbose_name='Is Good Credit Risk')),
                ('status', models.PositiveIntegerField(blank=True, null=True, verbose_name="Status of the debtor's checking account with the bank (categorical)")),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit duration in months (quantitative)')),
                ('credit_history', models.PositiveIntegerField(blank=True, null=True, verbose_name='History of compliance with previous or concurrent credit contracts (categorical)')),
                ('purpose', models.PositiveIntegerField(blank=True, null=True, verbose_name='Purpose for which the credit is needed (categorical)')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit amount in DM (quantitative)')),
                ('savings', models.PositiveIntegerField(blank=True, null=True, verbose_name="Debtor's savings (categorical)")),
                ('employment_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name="Duration of debtor's employment with current employer (ordinal; discrete quantitative)")),
                ('installment_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name="Credit installments as a percentage of debtor's disposable income (ordinal; discrete quantitative)")),
                ('personal_status_sex', models.PositiveIntegerField(blank=True, null=True, verbose_name='Combined information on sex and marital status; categorical')),
                ('other_debtors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Is there another debtor or a guarantor for the credit? (categorical)')),
                ('present_residence', models.PositiveIntegerField(blank=True, null=True, verbose_name='Length of time (in years) the debtor lives in the present residence (ordinal)')),
                ('most_valuable_property', models.PositiveIntegerField(blank=True, null=True, verbose_name="The debtor's most valuable property (choices)")),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age in years (quantitative)')),
                ('other_installment_plans', models.PositiveIntegerField(blank=True, null=True, verbose_name='Installment plans from providers other than the credit-giving bank (categorical)')),
                ('housing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Type of housing the debtor lives in (categorical)')),
                ('number_credits', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of credits including the current one the debtor has (or had) at this bank (ordinal, discretequantitative)')),
                ('job', models.PositiveIntegerField(blank=True, null=True, verbose_name="Quality of debtor's job (ordinal)")),
                ('people_liable', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of persons who financially depend on the debtor (i.e., are entitled to maintenance) (binary,discrete quantitative)')),
                ('has_telephone', models.BooleanField(blank=True, null=True, verbose_name="Is there a telephone landline registered on the debtor's name?")),
                ('is_foreign_worker', models.PositiveIntegerField(blank=True, null=True, verbose_name='Is the debtor a foreign worker?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_risk_parameters', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Parameter',
                'verbose_name_plural': 'Customer Parameters',
                'db_table': 'customer_parameters',
            },
        ),
    ]
