# Generated by Django 4.2.10 on 2024-02-22 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Title')),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pages')),
                ('cover_page', models.FileField(upload_to='')),
            ],
        ),
    ]
